<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PiezaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('piezas')->insert([
            [
                'tipo_pieza_id' => 1,
                'talla_id' => 3,
                'name' => 'Sombrero morenada varón',
                'valor_reposicion' => rand(20, 100),
                'alquiler_pieza' => rand(10, 50),
                'color' => '#000000',
                'material' => 'Fieltro',
                'notas' => 'Con decoraciones doradas.',
            ],
            [
                'tipo_pieza_id' => 2,
                'talla_id' => 4,
                'name' => 'Chaqueta morenada varón',
                'valor_reposicion' => rand(10, 50),
                'alquiler_pieza' => rand(10, 50),
                'color' => '#000000',
                'material' => 'Terciopelo',
                'notas' => null,
            ],
            [
                'tipo_pieza_id' => 5,
                'talla_id' => 4,
                'name' => 'Pantalón morenada varón',
                'valor_reposicion' => rand(10, 50),
                'alquiler_pieza' => rand(10, 50),
                'color' => '#000000',
                'material' => 'Lana',
                'notas' => null,
            ],
            [
                'tipo_pieza_id' => 7,
                'talla_id' => 10,
                'name' => 'Botas morenada varón',
                'valor_reposicion' => rand(10, 50),
                'alquiler_pieza' => rand(10, 50),
                'color' => '#000000',
                'material' => 'Cuero',
                'notas' => null,
            ],
            [
                'tipo_pieza_id' => 9,
                'talla_id' => 3,
                'name' => 'Máscara morenada varón',
                'valor_reposicion' => rand(10, 50),
                'alquiler_pieza' => rand(10, 50),
                'color' => '#FFCC00',
                'material' => 'Plástico',
                'notas' => 'Con bigotes y barba.',
            ],
            //morenada mujer
            [
                'tipo_pieza_id' => 3,
                'talla_id' => 3,
                'name' => 'Blusa morenada mujer',
                'valor_reposicion' => rand(10, 50),
                'alquiler_pieza' => rand(10, 50),
                'color' => '#FFFFFF',
                'material' => 'Seda',
                'notas' => null,
            ],
            [
                'tipo_pieza_id' => 4,
                'talla_id' => 3,
                'name' => 'Pollera morenada mujer',
                'valor_reposicion' => rand(10, 50),
                'alquiler_pieza' => rand(10, 50),
                'color' => '#FF0000',
                'material' => 'Lino',
                'notas' => 'Con detalles dorados.',
            ],
            [
                'tipo_pieza_id' => 6,
                'talla_id' => 3,
                'name' => 'Faja morenada mujer',
                'valor_reposicion' => rand(10, 50),
                'alquiler_pieza' => rand(10, 50),
                'color' => '#B22222',
                'material' => 'Tela gruesa',
                'notas' => null,
            ],
            [
                'tipo_pieza_id' => 8,
                'talla_id' => 4,
                'name' => 'Rebozo morenada mujer',
                'valor_reposicion' => rand(10, 50),
                'alquiler_pieza' => rand(10, 50),
                'color' => '#000000',
                'material' => 'Lana',
                'notas' => 'Con flecos.',
            ],
            [
                'tipo_pieza_id' => 7,
                'talla_id' => 7,
                'name' => 'Botas morenada mujer',
                'valor_reposicion' => rand(10, 50),
                'alquiler_pieza' => rand(10, 50),
                'color' => '#000000',
                'material' => 'Cuero',
                'notas' => null,
            ],
            //caporal hombre
            [
                'tipo_pieza_id' => 2,
                'talla_id' => 4,
                'name' => 'Chaqueta caporal varón',
                'valor_reposicion' => rand(10, 50),
                'alquiler_pieza' => rand(10, 50),
                'color' => '#0000FF',
                'material' => 'Lycra bordada',
                'notas' => null,
            ],
            [
                'tipo_pieza_id' => 5,
                'talla_id' => 4,
                'name' => 'Pantalón caporal varón',
                'valor_reposicion' => rand(10, 50),
                'alquiler_pieza' => rand(10, 50),
                'color' => '#0000FF',
                'material' => 'Lycra',
                'notas' => null,
            ],
            [
                'tipo_pieza_id' => 7,
                'talla_id' => 10,
                'name' => 'Botas caporal varón',
                'valor_reposicion' => rand(10, 50),
                'alquiler_pieza' => rand(10, 50),
                'color' => '#000000',
                'material' => 'Cuero',
                'notas' => 'Con plataforma y cascabeles.',
            ],
            [
                'tipo_pieza_id' => 14,
                'talla_id' => 12,
                'name' => 'Espuelas caporal varón',
                'valor_reposicion' => rand(10, 50),
                'alquiler_pieza' => rand(10, 50),
                'color' => '#C0C0C0',
                'material' => 'Metal',
                'notas' => null,
            ],
            [
                'tipo_pieza_id' => 15,
                'talla_id' => 12,
                'name' => 'Cascabeles caporal varón',
                'valor_reposicion' => rand(10, 50),
                'alquiler_pieza' => rand(10, 50),
                'color' => '#FFD700',
                'material' => 'Metal',
                'notas' => null,
            ],
            //caporal mujer
            [
                'tipo_pieza_id' => 3,
                'talla_id' => 3,
                'name' => 'Blusa caporal mujer',
                'valor_reposicion' => rand(10, 50),
                'alquiler_pieza' => rand(10, 50),
                'color' => '#FFFFFF',
                'material' => 'Encaje',
                'notas' => null,
            ],
            [
                'tipo_pieza_id' => 4,
                'talla_id' => 3,
                'name' => 'Falda caporal mujer',
                'valor_reposicion' => rand(10, 50),
                'alquiler_pieza' => rand(10, 50),
                'color' => '#0000FF',
                'material' => 'Tela bordada',
                'notas' => 'Falda corta con vuelo.',
            ],
            [
                'tipo_pieza_id' => 16,
                'talla_id' => 12,
                'name' => 'Tocado caporal mujer',
                'valor_reposicion' => rand(10, 50),
                'alquiler_pieza' => rand(10, 50),
                'color' => '#87CEFA',
                'material' => 'Plumas y lentejuelas',
                'notas' => null,
            ],
            [
                'tipo_pieza_id' => 7,
                'talla_id' => 7,
                'name' => 'Botas caporal mujer',
                'valor_reposicion' => rand(10, 50),
                'alquiler_pieza' => rand(10, 50),
                'color' => '#FFFFFF',
                'material' => 'Cuero',
                'notas' => null,
            ],
            [
                'tipo_pieza_id' => 15,
                'talla_id' => 12,
                'name' => 'Cascabeles caporal mujer',
                'valor_reposicion' => rand(10, 50),
                'alquiler_pieza' => rand(10, 50),
                'color' => '#FFD700',
                'material' => 'Metal',
                'notas' => null,
            ],
            [
                'tipo_pieza_id' => 2,
                'talla_id' => 4,
                'name' => 'Chaqueta tinku varón',
                'valor_reposicion' => rand(10, 50),
                'alquiler_pieza' => rand(10, 50),
                'color' => '#8B0000',
                'material' => 'Lana',
                'notas' => null,
            ],
            [
                'tipo_pieza_id' => 5,
                'talla_id' => 4,
                'name' => 'Pantalón tinku varón',
                'valor_reposicion' => rand(10, 50),
                'alquiler_pieza' => rand(10, 50),
                'color' => '#000000',
                'material' => 'Lana',
                'notas' => null,
            ],
            [
                'tipo_pieza_id' => 6,
                'talla_id' => 3,
                'name' => 'Faja tinku varón',
                'valor_reposicion' => rand(10, 50),
                'alquiler_pieza' => rand(10, 50),
                'color' => '#FF6347',
                'material' => 'Tela gruesa',
                'notas' => null,
            ],
            [
                'tipo_pieza_id' => 7,
                'talla_id' => 10,
                'name' => 'Botas tinku varón',
                'valor_reposicion' => rand(10, 50),
                'alquiler_pieza' => rand(10, 50),
                'color' => '#A52A2A',
                'material' => 'Cuero',
                'notas' => null,
            ],
            [
                'tipo_pieza_id' => 16,
                'talla_id' => 12,
                'name' => 'Tocado tinku varón',
                'valor_reposicion' => rand(10, 50),
                'alquiler_pieza' => rand(10, 50),
                'color' => '#DAA520',
                'material' => 'Lana',
                'notas' => 'Con pompones',
            ],
            [
                'tipo_pieza_id' => 3,
                'talla_id' => 3,
                'name' => 'Blusa tinku mujer',
                'valor_reposicion' => rand(10, 50),
                'alquiler_pieza' => rand(10, 50),
                'color' => '#FF69B4',
                'material' => 'Algodón',
                'notas' => null,
            ],
            [
                'tipo_pieza_id' => 4,
                'talla_id' => 3,
                'name' => 'Pollera tinku mujer',
                'valor_reposicion' => rand(10, 50),
                'alquiler_pieza' => rand(10, 50),
                'color' => '#800080',
                'material' => 'Tela bordada',
                'notas' => null,
            ],
            [
                'tipo_pieza_id' => 6,
                'talla_id' => 3,
                'name' => 'Faja tinku mujer',
                'valor_reposicion' => rand(10, 50),
                'alquiler_pieza' => rand(10, 50),
                'color' => '#FF4500',
                'material' => 'Lana',
                'notas' => null,
            ],
            [
                'tipo_pieza_id' => 7,
                'talla_id' => 8,
                'name' => 'Botas tinku mujer',
                'valor_reposicion' => rand(10, 50),
                'alquiler_pieza' => rand(10, 50),
                'color' => '#8B0000',
                'material' => 'Cuero',
                'notas' => null,
            ],
            [
                'tipo_pieza_id' => 16,
                'talla_id' => 12,
                'name' => 'Tocado tinku mujer',
                'valor_reposicion' => rand(10, 50),
                'alquiler_pieza' => rand(10, 50),
                'color' => '#FF1493',
                'material' => 'Tela y lana',
                'notas' => 'Con pompones y cintas',
            ],
            [
                'tipo_pieza_id' => 2,
                'talla_id' => 4,
                'name' => 'Chaqueta diablada varón',
                'valor_reposicion' => rand(10, 50),
                'alquiler_pieza' => rand(10, 50),
                'color' => '#00008B',
                'material' => 'Tela bordada',
                'notas' => null,
            ],
            [
                'tipo_pieza_id' => 5,
                'talla_id' => 4,
                'name' => 'Pantalón diablada varón',
                'valor_reposicion' => rand(10, 50),
                'alquiler_pieza' => rand(10, 50),
                'color' => '#8B0000',
                'material' => 'Tela bordada',
                'notas' => null,
            ],
            [
                'tipo_pieza_id' => 9,
                'talla_id' => 3,
                'name' => 'Máscara diablada varón',
                'valor_reposicion' => rand(10, 50),
                'alquiler_pieza' => rand(10, 50),
                'color' => '#FF8C00',
                'material' => 'Fibra de vidrio',
                'notas' => 'Con cuernos',
            ],
            [
                'tipo_pieza_id' => 10,
                'talla_id' => 12,
                'name' => 'Pechera diablada varón',
                'valor_reposicion' => rand(10, 50),
                'alquiler_pieza' => rand(10, 50),
                'color' => '#FFD700',
                'material' => 'Metal/plástico',
                'notas' => null,
            ],
            [
                'tipo_pieza_id' => 11,
                'talla_id' => 12,
                'name' => 'Capa diablada varón',
                'valor_reposicion' => rand(10, 50),
                'alquiler_pieza' => rand(10, 50),
                'color' => '#4B0082',
                'material' => 'Seda bordada',
                'notas' => null,
            ],
            [
                'tipo_pieza_id' => 3,
                'talla_id' => 3,
                'name' => 'Blusa diablada mujer',
                'valor_reposicion' => rand(10, 50),
                'alquiler_pieza' => rand(10, 50),
                'color' => '#FFB6C1',
                'material' => 'Seda',
                'notas' => null,
            ],
            [
                'tipo_pieza_id' => 4,
                'talla_id' => 3,
                'name' => 'Pollera diablada mujer',
                'valor_reposicion' => rand(10, 50),
                'alquiler_pieza' => rand(10, 50),
                'color' => '#9400D3',
                'material' => 'Tela bordada',
                'notas' => null,
            ],
            [
                'tipo_pieza_id' => 9,
                'talla_id' => 3,
                'name' => 'Máscara diablada mujer',
                'valor_reposicion' => rand(10, 50),
                'alquiler_pieza' => rand(10, 50),
                'color' => '#FF8C00',
                'material' => 'Fibra de vidrio',
                'notas' => null,
            ],
            [
                'tipo_pieza_id' => 10,
                'talla_id' => 12,
                'name' => 'Pechera diablada mujer',
                'valor_reposicion' => rand(10, 50),
                'alquiler_pieza' => rand(10, 50),
                'color' => '#DAA520',
                'material' => 'Metal/plástico',
                'notas' => null,
            ],
            [
                'tipo_pieza_id' => 11,
                'talla_id' => 12,
                'name' => 'Capa diablada mujer',
                'valor_reposicion' => rand(10, 50),
                'alquiler_pieza' => rand(10, 50),
                'color' => '#8A2BE2',
                'material' => 'Seda',
                'notas' => null,
            ],
            [
                'tipo_pieza_id' => 2,
                'talla_id' => 4,
                'name' => 'Chaqueta saya varón',
                'valor_reposicion' => rand(10, 50),
                'alquiler_pieza' => rand(10, 50),
                'color' => '#191970',
                'material' => 'Tela brillante',
                'notas' => null,
            ],
            [
                'tipo_pieza_id' => 5,
                'talla_id' => 4,
                'name' => 'Pantalón saya varón',
                'valor_reposicion' => rand(10, 50),
                'alquiler_pieza' => rand(10, 50),
                'color' => '#191970',
                'material' => 'Tela brillante',
                'notas' => null,
            ],
            [
                'tipo_pieza_id' => 7,
                'talla_id' => 10,
                'name' => 'Botas saya varón',
                'valor_reposicion' => rand(10, 50),
                'alquiler_pieza' => rand(10, 50),
                'color' => '#000000',
                'material' => 'Cuero',
                'notas' => null,
            ],
            [
                'tipo_pieza_id' => 15,
                'talla_id' => 12,
                'name' => 'Cascabeles saya varón',
                'valor_reposicion' => rand(10, 50),
                'alquiler_pieza' => rand(10, 50),
                'color' => '#FFD700',
                'material' => 'Metal',
                'notas' => null,
            ],
            [
                'tipo_pieza_id' => 14,
                'talla_id' => 12,
                'name' => 'Espuelas saya varón',
                'valor_reposicion' => rand(10, 50),
                'alquiler_pieza' => rand(10, 50),
                'color' => '#C0C0C0',
                'material' => 'Metal',
                'notas' => null,
            ],
            [
                'tipo_pieza_id' => 3,
                'talla_id' => 3,
                'name' => 'Blusa saya mujer',
                'valor_reposicion' => rand(10, 50),
                'alquiler_pieza' => rand(10, 50),
                'color' => '#ADD8E6',
                'material' => 'Encaje',
                'notas' => null,
            ],
            [
                'tipo_pieza_id' => 4,
                'talla_id' => 3,
                'name' => 'Falda saya mujer',
                'valor_reposicion' => rand(10, 50),
                'alquiler_pieza' => rand(10, 50),
                'color' => '#4169E1',
                'material' => 'Tela brillante',
                'notas' => 'Falda corta con vuelo',
            ],
            [
                'tipo_pieza_id' => 7,
                'talla_id' => 8,
                'name' => 'Botas saya mujer',
                'valor_reposicion' => rand(10, 50),
                'alquiler_pieza' => rand(10, 50),
                'color' => '#FFFFFF',
                'material' => 'Cuero',
                'notas' => null,
            ],
            [
                'tipo_pieza_id' => 15,
                'talla_id' => 12,
                'name' => 'Cascabeles saya mujer',
                'valor_reposicion' => rand(10, 50),
                'alquiler_pieza' => rand(10, 50),
                'color' => '#FFD700',
                'material' => 'Metal',
                'notas' => null,
            ],
            [
                'tipo_pieza_id' => 16,
                'talla_id' => 12,
                'name' => 'Tocado saya mujer',
                'valor_reposicion' => rand(10, 50),
                'alquiler_pieza' => rand(10, 50),
                'color' => '#ADD8E6',
                'material' => 'Tela y lentejuelas',
                'notas' => null,
            ],
        ]);
    }
}
